FROM openjdk:17.0.2-jdk-slim
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
CMD ["java", "-Dspring.profiles.active=prod","-jar", "app.jar"]
# CMD ["./wait-for-it.sh", "db:3306", "--", "java", "-Dspring.profiles.active=prod","-jar", "app.jar"]